/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using FileParameter = LineOpenApi.MessagingApi.Client.FileParameter;
using OpenAPIDateConverter = LineOpenApi.MessagingApi.Client.OpenAPIDateConverter;

namespace LineOpenApi.MessagingApi.Model
{
    /// <summary>
    /// AudioMessage
    /// </summary>
    [DataContract(Name = "AudioMessage")]
    [JsonConverter(typeof(JsonSubtypes), "Type")]
    public partial class AudioMessage : Message, IEquatable<AudioMessage>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AudioMessage" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AudioMessage() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AudioMessage" /> class.
        /// </summary>
        /// <param name="originalContentUrl">originalContentUrl (required).</param>
        /// <param name="duration">duration (required).</param>
        /// <param name="type">Type of message (required) (default to &quot;AudioMessage&quot;).</param>
        /// <param name="quickReply">quickReply.</param>
        /// <param name="sender">sender.</param>
        public AudioMessage(string originalContentUrl = default(string), long duration = default(long), string type = @"audio", QuickReply quickReply = default(QuickReply), Sender sender = default(Sender)) : base(type, quickReply, sender)
        {
            // to ensure "originalContentUrl" is required (not null)
            if (originalContentUrl == null)
            {
                throw new ArgumentNullException("originalContentUrl is a required property for AudioMessage and cannot be null");
            }
            this.OriginalContentUrl = originalContentUrl;
            this.Duration = duration;
        }

        /// <summary>
        /// Gets or Sets OriginalContentUrl
        /// </summary>
        [DataMember(Name = "originalContentUrl", IsRequired = true, EmitDefaultValue = true)]
        public string OriginalContentUrl { get; set; }

        /// <summary>
        /// Gets or Sets Duration
        /// </summary>
        [DataMember(Name = "duration", IsRequired = true, EmitDefaultValue = true)]
        public long Duration { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AudioMessage {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  OriginalContentUrl: ").Append(OriginalContentUrl).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AudioMessage);
        }

        /// <summary>
        /// Returns true if AudioMessage instances are equal
        /// </summary>
        /// <param name="input">Instance of AudioMessage to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AudioMessage input)
        {
            if (input == null)
            {
                return false;
            }
            return base.Equals(input) && 
                (
                    this.OriginalContentUrl == input.OriginalContentUrl ||
                    (this.OriginalContentUrl != null &&
                    this.OriginalContentUrl.Equals(input.OriginalContentUrl))
                ) && base.Equals(input) && 
                (
                    this.Duration == input.Duration ||
                    this.Duration.Equals(input.Duration)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.OriginalContentUrl != null)
                {
                    hashCode = (hashCode * 59) + this.OriginalContentUrl.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Duration.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
