/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = LineOpenApi.MessagingApi.Client.FileParameter;
using OpenAPIDateConverter = LineOpenApi.MessagingApi.Client.OpenAPIDateConverter;

namespace LineOpenApi.MessagingApi.Model
{
    /// <summary>
    /// CreateRichMenuAliasRequest
    /// </summary>
    [DataContract(Name = "CreateRichMenuAliasRequest")]
    public partial class CreateRichMenuAliasRequest : IEquatable<CreateRichMenuAliasRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateRichMenuAliasRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateRichMenuAliasRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateRichMenuAliasRequest" /> class.
        /// </summary>
        /// <param name="richMenuAliasId">Rich menu alias ID, which can be any ID, unique for each channel. (required).</param>
        /// <param name="richMenuId">The rich menu ID to be associated with the rich menu alias. (required).</param>
        public CreateRichMenuAliasRequest(string richMenuAliasId = default(string), string richMenuId = default(string))
        {
            // to ensure "richMenuAliasId" is required (not null)
            if (richMenuAliasId == null)
            {
                throw new ArgumentNullException("richMenuAliasId is a required property for CreateRichMenuAliasRequest and cannot be null");
            }
            this.RichMenuAliasId = richMenuAliasId;
            // to ensure "richMenuId" is required (not null)
            if (richMenuId == null)
            {
                throw new ArgumentNullException("richMenuId is a required property for CreateRichMenuAliasRequest and cannot be null");
            }
            this.RichMenuId = richMenuId;
        }

        /// <summary>
        /// Rich menu alias ID, which can be any ID, unique for each channel.
        /// </summary>
        /// <value>Rich menu alias ID, which can be any ID, unique for each channel.</value>
        [DataMember(Name = "richMenuAliasId", IsRequired = true, EmitDefaultValue = true)]
        public string RichMenuAliasId { get; set; }

        /// <summary>
        /// The rich menu ID to be associated with the rich menu alias.
        /// </summary>
        /// <value>The rich menu ID to be associated with the rich menu alias.</value>
        [DataMember(Name = "richMenuId", IsRequired = true, EmitDefaultValue = true)]
        public string RichMenuId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateRichMenuAliasRequest {\n");
            sb.Append("  RichMenuAliasId: ").Append(RichMenuAliasId).Append("\n");
            sb.Append("  RichMenuId: ").Append(RichMenuId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateRichMenuAliasRequest);
        }

        /// <summary>
        /// Returns true if CreateRichMenuAliasRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateRichMenuAliasRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateRichMenuAliasRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.RichMenuAliasId == input.RichMenuAliasId ||
                    (this.RichMenuAliasId != null &&
                    this.RichMenuAliasId.Equals(input.RichMenuAliasId))
                ) && 
                (
                    this.RichMenuId == input.RichMenuId ||
                    (this.RichMenuId != null &&
                    this.RichMenuId.Equals(input.RichMenuId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RichMenuAliasId != null)
                {
                    hashCode = (hashCode * 59) + this.RichMenuAliasId.GetHashCode();
                }
                if (this.RichMenuId != null)
                {
                    hashCode = (hashCode * 59) + this.RichMenuId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // RichMenuAliasId (string) maxLength
            if (this.RichMenuAliasId != null && this.RichMenuAliasId.Length > 32)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for RichMenuAliasId, length must be less than 32.", new [] { "RichMenuAliasId" });
            }

            // RichMenuAliasId (string) minLength
            if (this.RichMenuAliasId != null && this.RichMenuAliasId.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for RichMenuAliasId, length must be greater than 1.", new [] { "RichMenuAliasId" });
            }

            if (this.RichMenuAliasId != null) {
                // RichMenuAliasId (string) pattern
                Regex regexRichMenuAliasId = new Regex(@"^[a-z0-9_-]{1,32}$", RegexOptions.CultureInvariant);
                if (!regexRichMenuAliasId.Match(this.RichMenuAliasId).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for RichMenuAliasId, must match a pattern of " + regexRichMenuAliasId, new [] { "RichMenuAliasId" });
                }
            }

            yield break;
        }
    }

}
