/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = LineOpenApi.MessagingApi.Client.FileParameter;
using OpenAPIDateConverter = LineOpenApi.MessagingApi.Client.OpenAPIDateConverter;

namespace LineOpenApi.MessagingApi.Model
{
    /// <summary>
    /// ImagemapVideo
    /// </summary>
    [DataContract(Name = "ImagemapVideo")]
    public partial class ImagemapVideo : IEquatable<ImagemapVideo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ImagemapVideo" /> class.
        /// </summary>
        /// <param name="originalContentUrl">originalContentUrl.</param>
        /// <param name="previewImageUrl">previewImageUrl.</param>
        /// <param name="area">area.</param>
        /// <param name="externalLink">externalLink.</param>
        public ImagemapVideo(string originalContentUrl = default(string), string previewImageUrl = default(string), ImagemapArea area = default(ImagemapArea), ImagemapExternalLink externalLink = default(ImagemapExternalLink))
        {
            this.OriginalContentUrl = originalContentUrl;
            this.PreviewImageUrl = previewImageUrl;
            this.Area = area;
            this.ExternalLink = externalLink;
        }

        /// <summary>
        /// Gets or Sets OriginalContentUrl
        /// </summary>
        [DataMember(Name = "originalContentUrl", EmitDefaultValue = false)]
        public string OriginalContentUrl { get; set; }

        /// <summary>
        /// Gets or Sets PreviewImageUrl
        /// </summary>
        [DataMember(Name = "previewImageUrl", EmitDefaultValue = false)]
        public string PreviewImageUrl { get; set; }

        /// <summary>
        /// Gets or Sets Area
        /// </summary>
        [DataMember(Name = "area", EmitDefaultValue = false)]
        public ImagemapArea Area { get; set; }

        /// <summary>
        /// Gets or Sets ExternalLink
        /// </summary>
        [DataMember(Name = "externalLink", EmitDefaultValue = false)]
        public ImagemapExternalLink ExternalLink { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ImagemapVideo {\n");
            sb.Append("  OriginalContentUrl: ").Append(OriginalContentUrl).Append("\n");
            sb.Append("  PreviewImageUrl: ").Append(PreviewImageUrl).Append("\n");
            sb.Append("  Area: ").Append(Area).Append("\n");
            sb.Append("  ExternalLink: ").Append(ExternalLink).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ImagemapVideo);
        }

        /// <summary>
        /// Returns true if ImagemapVideo instances are equal
        /// </summary>
        /// <param name="input">Instance of ImagemapVideo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ImagemapVideo input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.OriginalContentUrl == input.OriginalContentUrl ||
                    (this.OriginalContentUrl != null &&
                    this.OriginalContentUrl.Equals(input.OriginalContentUrl))
                ) && 
                (
                    this.PreviewImageUrl == input.PreviewImageUrl ||
                    (this.PreviewImageUrl != null &&
                    this.PreviewImageUrl.Equals(input.PreviewImageUrl))
                ) && 
                (
                    this.Area == input.Area ||
                    (this.Area != null &&
                    this.Area.Equals(input.Area))
                ) && 
                (
                    this.ExternalLink == input.ExternalLink ||
                    (this.ExternalLink != null &&
                    this.ExternalLink.Equals(input.ExternalLink))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OriginalContentUrl != null)
                {
                    hashCode = (hashCode * 59) + this.OriginalContentUrl.GetHashCode();
                }
                if (this.PreviewImageUrl != null)
                {
                    hashCode = (hashCode * 59) + this.PreviewImageUrl.GetHashCode();
                }
                if (this.Area != null)
                {
                    hashCode = (hashCode * 59) + this.Area.GetHashCode();
                }
                if (this.ExternalLink != null)
                {
                    hashCode = (hashCode * 59) + this.ExternalLink.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
