/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using FileParameter = LineOpenApi.MessagingApi.Client.FileParameter;
using OpenAPIDateConverter = LineOpenApi.MessagingApi.Client.OpenAPIDateConverter;

namespace LineOpenApi.MessagingApi.Model
{
    /// <summary>
    /// PostbackAction
    /// </summary>
    [DataContract(Name = "PostbackAction")]
    [JsonConverter(typeof(JsonSubtypes), "Type")]
    public partial class PostbackAction : Action, IEquatable<PostbackAction>, IValidatableObject
    {
        /// <summary>
        /// Defines InputOption
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum InputOptionEnum
        {
            /// <summary>
            /// Enum CloseRichMenu for value: closeRichMenu
            /// </summary>
            [EnumMember(Value = "closeRichMenu")]
            CloseRichMenu = 1,

            /// <summary>
            /// Enum OpenRichMenu for value: openRichMenu
            /// </summary>
            [EnumMember(Value = "openRichMenu")]
            OpenRichMenu = 2,

            /// <summary>
            /// Enum OpenKeyboard for value: openKeyboard
            /// </summary>
            [EnumMember(Value = "openKeyboard")]
            OpenKeyboard = 3,

            /// <summary>
            /// Enum OpenVoice for value: openVoice
            /// </summary>
            [EnumMember(Value = "openVoice")]
            OpenVoice = 4
        }


        /// <summary>
        /// Gets or Sets InputOption
        /// </summary>
        [DataMember(Name = "inputOption", EmitDefaultValue = false)]
        public InputOptionEnum? InputOption { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PostbackAction" /> class.
        /// </summary>
        /// <param name="data">data.</param>
        /// <param name="displayText">displayText.</param>
        /// <param name="text">text.</param>
        /// <param name="inputOption">inputOption.</param>
        /// <param name="fillInText">fillInText.</param>
        /// <param name="type">Type of action (default to &quot;PostbackAction&quot;).</param>
        /// <param name="label">Label for the action..</param>
        public PostbackAction(string data = default(string), string displayText = default(string), string text = default(string), InputOptionEnum? inputOption = default(InputOptionEnum?), string fillInText = default(string), string type = @"PostbackAction", string label = default(string)) : base(type, label)
        {
            this.Data = data;
            this.DisplayText = displayText;
            this.Text = text;
            this.InputOption = inputOption;
            this.FillInText = fillInText;
        }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name = "data", EmitDefaultValue = false)]
        public string Data { get; set; }

        /// <summary>
        /// Gets or Sets DisplayText
        /// </summary>
        [DataMember(Name = "displayText", EmitDefaultValue = false)]
        public string DisplayText { get; set; }

        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        [DataMember(Name = "text", EmitDefaultValue = false)]
        public string Text { get; set; }

        /// <summary>
        /// Gets or Sets FillInText
        /// </summary>
        [DataMember(Name = "fillInText", EmitDefaultValue = false)]
        public string FillInText { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostbackAction {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  DisplayText: ").Append(DisplayText).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  InputOption: ").Append(InputOption).Append("\n");
            sb.Append("  FillInText: ").Append(FillInText).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PostbackAction);
        }

        /// <summary>
        /// Returns true if PostbackAction instances are equal
        /// </summary>
        /// <param name="input">Instance of PostbackAction to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PostbackAction input)
        {
            if (input == null)
            {
                return false;
            }
            return base.Equals(input) && 
                (
                    this.Data == input.Data ||
                    (this.Data != null &&
                    this.Data.Equals(input.Data))
                ) && base.Equals(input) && 
                (
                    this.DisplayText == input.DisplayText ||
                    (this.DisplayText != null &&
                    this.DisplayText.Equals(input.DisplayText))
                ) && base.Equals(input) && 
                (
                    this.Text == input.Text ||
                    (this.Text != null &&
                    this.Text.Equals(input.Text))
                ) && base.Equals(input) && 
                (
                    this.InputOption == input.InputOption ||
                    this.InputOption.Equals(input.InputOption)
                ) && base.Equals(input) && 
                (
                    this.FillInText == input.FillInText ||
                    (this.FillInText != null &&
                    this.FillInText.Equals(input.FillInText))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Data != null)
                {
                    hashCode = (hashCode * 59) + this.Data.GetHashCode();
                }
                if (this.DisplayText != null)
                {
                    hashCode = (hashCode * 59) + this.DisplayText.GetHashCode();
                }
                if (this.Text != null)
                {
                    hashCode = (hashCode * 59) + this.Text.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.InputOption.GetHashCode();
                if (this.FillInText != null)
                {
                    hashCode = (hashCode * 59) + this.FillInText.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            // Data (string) maxLength
            if (this.Data != null && this.Data.Length > 300)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Data, length must be less than 300.", new [] { "Data" });
            }

            // Data (string) minLength
            if (this.Data != null && this.Data.Length < 0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Data, length must be greater than 0.", new [] { "Data" });
            }

            yield break;
        }
    }

}
