/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = LineOpenApi.MessagingApi.Client.FileParameter;
using OpenAPIDateConverter = LineOpenApi.MessagingApi.Client.OpenAPIDateConverter;

namespace LineOpenApi.MessagingApi.Model
{
    /// <summary>
    /// QuotaConsumptionResponse
    /// </summary>
    [DataContract(Name = "QuotaConsumptionResponse")]
    public partial class QuotaConsumptionResponse : IEquatable<QuotaConsumptionResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QuotaConsumptionResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected QuotaConsumptionResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="QuotaConsumptionResponse" /> class.
        /// </summary>
        /// <param name="totalUsage">The number of sent messages in the current month (required).</param>
        public QuotaConsumptionResponse(long totalUsage = default(long))
        {
            this.TotalUsage = totalUsage;
        }

        /// <summary>
        /// The number of sent messages in the current month
        /// </summary>
        /// <value>The number of sent messages in the current month</value>
        [DataMember(Name = "totalUsage", IsRequired = true, EmitDefaultValue = true)]
        public long TotalUsage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QuotaConsumptionResponse {\n");
            sb.Append("  TotalUsage: ").Append(TotalUsage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as QuotaConsumptionResponse);
        }

        /// <summary>
        /// Returns true if QuotaConsumptionResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of QuotaConsumptionResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QuotaConsumptionResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TotalUsage == input.TotalUsage ||
                    this.TotalUsage.Equals(input.TotalUsage)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.TotalUsage.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
