/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = LineOpenApi.MessagingApi.Client.FileParameter;
using OpenAPIDateConverter = LineOpenApi.MessagingApi.Client.OpenAPIDateConverter;

namespace LineOpenApi.MessagingApi.Model
{
    /// <summary>
    /// ReplyMessageResponse
    /// </summary>
    [DataContract(Name = "ReplyMessageResponse")]
    public partial class ReplyMessageResponse : IEquatable<ReplyMessageResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReplyMessageResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ReplyMessageResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReplyMessageResponse" /> class.
        /// </summary>
        /// <param name="sentMessages">Array of sent messages. (required).</param>
        public ReplyMessageResponse(List<SentMessage> sentMessages = default(List<SentMessage>))
        {
            // to ensure "sentMessages" is required (not null)
            if (sentMessages == null)
            {
                throw new ArgumentNullException("sentMessages is a required property for ReplyMessageResponse and cannot be null");
            }
            this.SentMessages = sentMessages;
        }

        /// <summary>
        /// Array of sent messages.
        /// </summary>
        /// <value>Array of sent messages.</value>
        [DataMember(Name = "sentMessages", IsRequired = true, EmitDefaultValue = true)]
        public List<SentMessage> SentMessages { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReplyMessageResponse {\n");
            sb.Append("  SentMessages: ").Append(SentMessages).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReplyMessageResponse);
        }

        /// <summary>
        /// Returns true if ReplyMessageResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ReplyMessageResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReplyMessageResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.SentMessages == input.SentMessages ||
                    this.SentMessages != null &&
                    input.SentMessages != null &&
                    this.SentMessages.SequenceEqual(input.SentMessages)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SentMessages != null)
                {
                    hashCode = (hashCode * 59) + this.SentMessages.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
