/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = LineOpenApi.MessagingApi.Client.FileParameter;
using OpenAPIDateConverter = LineOpenApi.MessagingApi.Client.OpenAPIDateConverter;

namespace LineOpenApi.MessagingApi.Model
{
    /// <summary>
    /// RichMenuIdResponse
    /// </summary>
    [DataContract(Name = "RichMenuIdResponse")]
    public partial class RichMenuIdResponse : IEquatable<RichMenuIdResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RichMenuIdResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RichMenuIdResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RichMenuIdResponse" /> class.
        /// </summary>
        /// <param name="richMenuId">Rich menu ID (required).</param>
        public RichMenuIdResponse(string richMenuId = default(string))
        {
            // to ensure "richMenuId" is required (not null)
            if (richMenuId == null)
            {
                throw new ArgumentNullException("richMenuId is a required property for RichMenuIdResponse and cannot be null");
            }
            this.RichMenuId = richMenuId;
        }

        /// <summary>
        /// Rich menu ID
        /// </summary>
        /// <value>Rich menu ID</value>
        [DataMember(Name = "richMenuId", IsRequired = true, EmitDefaultValue = true)]
        public string RichMenuId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RichMenuIdResponse {\n");
            sb.Append("  RichMenuId: ").Append(RichMenuId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RichMenuIdResponse);
        }

        /// <summary>
        /// Returns true if RichMenuIdResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of RichMenuIdResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RichMenuIdResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.RichMenuId == input.RichMenuId ||
                    (this.RichMenuId != null &&
                    this.RichMenuId.Equals(input.RichMenuId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RichMenuId != null)
                {
                    hashCode = (hashCode * 59) + this.RichMenuId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
