/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = LineOpenApi.MessagingApi.Client.FileParameter;
using OpenAPIDateConverter = LineOpenApi.MessagingApi.Client.OpenAPIDateConverter;

namespace LineOpenApi.MessagingApi.Model
{
    /// <summary>
    /// SetWebhookEndpointRequest
    /// </summary>
    [DataContract(Name = "SetWebhookEndpointRequest")]
    public partial class SetWebhookEndpointRequest : IEquatable<SetWebhookEndpointRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetWebhookEndpointRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SetWebhookEndpointRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SetWebhookEndpointRequest" /> class.
        /// </summary>
        /// <param name="endpoint">A valid webhook URL. (required).</param>
        public SetWebhookEndpointRequest(string endpoint = default(string))
        {
            // to ensure "endpoint" is required (not null)
            if (endpoint == null)
            {
                throw new ArgumentNullException("endpoint is a required property for SetWebhookEndpointRequest and cannot be null");
            }
            this.Endpoint = endpoint;
        }

        /// <summary>
        /// A valid webhook URL.
        /// </summary>
        /// <value>A valid webhook URL.</value>
        [DataMember(Name = "endpoint", IsRequired = true, EmitDefaultValue = true)]
        public string Endpoint { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SetWebhookEndpointRequest {\n");
            sb.Append("  Endpoint: ").Append(Endpoint).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SetWebhookEndpointRequest);
        }

        /// <summary>
        /// Returns true if SetWebhookEndpointRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SetWebhookEndpointRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SetWebhookEndpointRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Endpoint == input.Endpoint ||
                    (this.Endpoint != null &&
                    this.Endpoint.Equals(input.Endpoint))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Endpoint != null)
                {
                    hashCode = (hashCode * 59) + this.Endpoint.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Endpoint (string) maxLength
            if (this.Endpoint != null && this.Endpoint.Length > 500)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Endpoint, length must be less than 500.", new [] { "Endpoint" });
            }

            // Endpoint (string) minLength
            if (this.Endpoint != null && this.Endpoint.Length < 0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Endpoint, length must be greater than 0.", new [] { "Endpoint" });
            }

            yield break;
        }
    }

}
