/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using FileParameter = LineOpenApi.Webhook.Client.FileParameter;
using OpenAPIDateConverter = LineOpenApi.Webhook.Client.OpenAPIDateConverter;

namespace LineOpenApi.Webhook.Model
{
    /// <summary>
    /// DetachedModuleContent
    /// </summary>
    [DataContract(Name = "DetachedModuleContent")]
    public partial class DetachedModuleContent : ModuleContent, IEquatable<DetachedModuleContent>, IValidatableObject
    {
        /// <summary>
        /// Reason for detaching
        /// </summary>
        /// <value>Reason for detaching</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ReasonEnum
        {
            /// <summary>
            /// Enum BotDeleted for value: bot_deleted
            /// </summary>
            [EnumMember(Value = "bot_deleted")]
            BotDeleted = 1
        }


        /// <summary>
        /// Reason for detaching
        /// </summary>
        /// <value>Reason for detaching</value>
        [DataMember(Name = "reason", IsRequired = true, EmitDefaultValue = true)]
        public ReasonEnum Reason { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DetachedModuleContent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DetachedModuleContent() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DetachedModuleContent" /> class.
        /// </summary>
        /// <param name="botId">Detached LINE Official Account bot user ID (required).</param>
        /// <param name="reason">Reason for detaching (required).</param>
        /// <param name="type">Type (required) (default to &quot;DetachedModuleContent&quot;).</param>
        public DetachedModuleContent(string botId = default(string), ReasonEnum reason = default(ReasonEnum), string type = @"DetachedModuleContent") : base(type)
        {
            // to ensure "botId" is required (not null)
            if (botId == null)
            {
                throw new ArgumentNullException("botId is a required property for DetachedModuleContent and cannot be null");
            }
            this.BotId = botId;
            this.Reason = reason;
        }

        /// <summary>
        /// Detached LINE Official Account bot user ID
        /// </summary>
        /// <value>Detached LINE Official Account bot user ID</value>
        [DataMember(Name = "botId", IsRequired = true, EmitDefaultValue = true)]
        public string BotId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DetachedModuleContent {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  BotId: ").Append(BotId).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DetachedModuleContent);
        }

        /// <summary>
        /// Returns true if DetachedModuleContent instances are equal
        /// </summary>
        /// <param name="input">Instance of DetachedModuleContent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DetachedModuleContent input)
        {
            if (input == null)
            {
                return false;
            }
            return base.Equals(input) && 
                (
                    this.BotId == input.BotId ||
                    (this.BotId != null &&
                    this.BotId.Equals(input.BotId))
                ) && base.Equals(input) && 
                (
                    this.Reason == input.Reason ||
                    this.Reason.Equals(input.Reason)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.BotId != null)
                {
                    hashCode = (hashCode * 59) + this.BotId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Reason.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
