/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using FileParameter = LineOpenApi.Webhook.Client.FileParameter;
using OpenAPIDateConverter = LineOpenApi.Webhook.Client.OpenAPIDateConverter;

namespace LineOpenApi.Webhook.Model
{
    /// <summary>
    /// RenewedMembershipContent
    /// </summary>
    [DataContract(Name = "RenewedMembershipContent")]
    public partial class RenewedMembershipContent : MembershipContent, IEquatable<RenewedMembershipContent>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RenewedMembershipContent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RenewedMembershipContent() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RenewedMembershipContent" /> class.
        /// </summary>
        /// <param name="membershipId">The ID of the membership that the user renewed. This is defined for each membership. (required).</param>
        /// <param name="type">Type of membership event. (required) (default to &quot;RenewedMembershipContent&quot;).</param>
        public RenewedMembershipContent(int membershipId = default(int), string type = @"RenewedMembershipContent") : base(type)
        {
            this.MembershipId = membershipId;
        }

        /// <summary>
        /// The ID of the membership that the user renewed. This is defined for each membership.
        /// </summary>
        /// <value>The ID of the membership that the user renewed. This is defined for each membership.</value>
        [DataMember(Name = "membershipId", IsRequired = true, EmitDefaultValue = true)]
        public int MembershipId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RenewedMembershipContent {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  MembershipId: ").Append(MembershipId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RenewedMembershipContent);
        }

        /// <summary>
        /// Returns true if RenewedMembershipContent instances are equal
        /// </summary>
        /// <param name="input">Instance of RenewedMembershipContent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RenewedMembershipContent input)
        {
            if (input == null)
            {
                return false;
            }
            return base.Equals(input) && 
                (
                    this.MembershipId == input.MembershipId ||
                    this.MembershipId.Equals(input.MembershipId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                hashCode = (hashCode * 59) + this.MembershipId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
