/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing AgeDemographicFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AgeDemographicFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AgeDemographicFilter
        //private AgeDemographicFilter instance;

        public AgeDemographicFilterTests()
        {
            // TODO uncomment below to create an instance of AgeDemographicFilter
            //instance = new AgeDemographicFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AgeDemographicFilter
        /// </summary>
        [Fact]
        public void AgeDemographicFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" AgeDemographicFilter
            //Assert.IsType<AgeDemographicFilter>(instance);
        }

        /// <summary>
        /// Test the property 'Gte'
        /// </summary>
        [Fact]
        public void GteTest()
        {
            // TODO unit test for the property 'Gte'
        }

        /// <summary>
        /// Test the property 'Lt'
        /// </summary>
        [Fact]
        public void LtTest()
        {
            // TODO unit test for the property 'Lt'
        }
    }
}
