/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing AreaDemographicFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AreaDemographicFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AreaDemographicFilter
        //private AreaDemographicFilter instance;

        public AreaDemographicFilterTests()
        {
            // TODO uncomment below to create an instance of AreaDemographicFilter
            //instance = new AreaDemographicFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AreaDemographicFilter
        /// </summary>
        [Fact]
        public void AreaDemographicFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" AreaDemographicFilter
            //Assert.IsType<AreaDemographicFilter>(instance);
        }

        /// <summary>
        /// Test the property 'OneOf'
        /// </summary>
        [Fact]
        public void OneOfTest()
        {
            // TODO unit test for the property 'OneOf'
        }
    }
}
