/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing EmojiSubstitutionObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmojiSubstitutionObjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmojiSubstitutionObject
        //private EmojiSubstitutionObject instance;

        public EmojiSubstitutionObjectTests()
        {
            // TODO uncomment below to create an instance of EmojiSubstitutionObject
            //instance = new EmojiSubstitutionObject();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmojiSubstitutionObject
        /// </summary>
        [Fact]
        public void EmojiSubstitutionObjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmojiSubstitutionObject
            //Assert.IsType<EmojiSubstitutionObject>(instance);
        }

        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Fact]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }

        /// <summary>
        /// Test the property 'EmojiId'
        /// </summary>
        [Fact]
        public void EmojiIdTest()
        {
            // TODO unit test for the property 'EmojiId'
        }
    }
}
