/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing Filter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Filter
        //private Filter instance;

        public FilterTests()
        {
            // TODO uncomment below to create an instance of Filter
            //instance = new Filter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Filter
        /// </summary>
        [Fact]
        public void FilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" Filter
            //Assert.IsType<Filter>(instance);
        }

        /// <summary>
        /// Test the property 'Demographic'
        /// </summary>
        [Fact]
        public void DemographicTest()
        {
            // TODO unit test for the property 'Demographic'
        }
    }
}
