/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing FlexBubbleStyles
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FlexBubbleStylesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FlexBubbleStyles
        //private FlexBubbleStyles instance;

        public FlexBubbleStylesTests()
        {
            // TODO uncomment below to create an instance of FlexBubbleStyles
            //instance = new FlexBubbleStyles();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FlexBubbleStyles
        /// </summary>
        [Fact]
        public void FlexBubbleStylesInstanceTest()
        {
            // TODO uncomment below to test "IsType" FlexBubbleStyles
            //Assert.IsType<FlexBubbleStyles>(instance);
        }

        /// <summary>
        /// Test the property 'Header'
        /// </summary>
        [Fact]
        public void HeaderTest()
        {
            // TODO unit test for the property 'Header'
        }

        /// <summary>
        /// Test the property 'Hero'
        /// </summary>
        [Fact]
        public void HeroTest()
        {
            // TODO unit test for the property 'Hero'
        }

        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Fact]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }

        /// <summary>
        /// Test the property 'Footer'
        /// </summary>
        [Fact]
        public void FooterTest()
        {
            // TODO unit test for the property 'Footer'
        }
    }
}
