/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing FlexOffset
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FlexOffsetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FlexOffset
        //private FlexOffset instance;

        public FlexOffsetTests()
        {
            // TODO uncomment below to create an instance of FlexOffset
            //instance = new FlexOffset();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FlexOffset
        /// </summary>
        [Fact]
        public void FlexOffsetInstanceTest()
        {
            // TODO uncomment below to test "IsType" FlexOffset
            //Assert.IsType<FlexOffset>(instance);
        }
    }
}
