/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing FlexVideo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FlexVideoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FlexVideo
        //private FlexVideo instance;

        public FlexVideoTests()
        {
            // TODO uncomment below to create an instance of FlexVideo
            //instance = new FlexVideo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FlexVideo
        /// </summary>
        [Fact]
        public void FlexVideoInstanceTest()
        {
            // TODO uncomment below to test "IsType" FlexVideo
            //Assert.IsType<FlexVideo>(instance);
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'PreviewUrl'
        /// </summary>
        [Fact]
        public void PreviewUrlTest()
        {
            // TODO unit test for the property 'PreviewUrl'
        }

        /// <summary>
        /// Test the property 'AltContent'
        /// </summary>
        [Fact]
        public void AltContentTest()
        {
            // TODO unit test for the property 'AltContent'
        }

        /// <summary>
        /// Test the property 'AspectRatio'
        /// </summary>
        [Fact]
        public void AspectRatioTest()
        {
            // TODO unit test for the property 'AspectRatio'
        }

        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
    }
}
