/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing GroupSummaryResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GroupSummaryResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GroupSummaryResponse
        //private GroupSummaryResponse instance;

        public GroupSummaryResponseTests()
        {
            // TODO uncomment below to create an instance of GroupSummaryResponse
            //instance = new GroupSummaryResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GroupSummaryResponse
        /// </summary>
        [Fact]
        public void GroupSummaryResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GroupSummaryResponse
            //Assert.IsType<GroupSummaryResponse>(instance);
        }

        /// <summary>
        /// Test the property 'GroupId'
        /// </summary>
        [Fact]
        public void GroupIdTest()
        {
            // TODO unit test for the property 'GroupId'
        }

        /// <summary>
        /// Test the property 'GroupName'
        /// </summary>
        [Fact]
        public void GroupNameTest()
        {
            // TODO unit test for the property 'GroupName'
        }

        /// <summary>
        /// Test the property 'PictureUrl'
        /// </summary>
        [Fact]
        public void PictureUrlTest()
        {
            // TODO unit test for the property 'PictureUrl'
        }
    }
}
