/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing ImagemapVideo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ImagemapVideoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ImagemapVideo
        //private ImagemapVideo instance;

        public ImagemapVideoTests()
        {
            // TODO uncomment below to create an instance of ImagemapVideo
            //instance = new ImagemapVideo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImagemapVideo
        /// </summary>
        [Fact]
        public void ImagemapVideoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ImagemapVideo
            //Assert.IsType<ImagemapVideo>(instance);
        }

        /// <summary>
        /// Test the property 'OriginalContentUrl'
        /// </summary>
        [Fact]
        public void OriginalContentUrlTest()
        {
            // TODO unit test for the property 'OriginalContentUrl'
        }

        /// <summary>
        /// Test the property 'PreviewImageUrl'
        /// </summary>
        [Fact]
        public void PreviewImageUrlTest()
        {
            // TODO unit test for the property 'PreviewImageUrl'
        }

        /// <summary>
        /// Test the property 'Area'
        /// </summary>
        [Fact]
        public void AreaTest()
        {
            // TODO unit test for the property 'Area'
        }

        /// <summary>
        /// Test the property 'ExternalLink'
        /// </summary>
        [Fact]
        public void ExternalLinkTest()
        {
            // TODO unit test for the property 'ExternalLink'
        }
    }
}
