/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing ImagemapMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ImagemapMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ImagemapMessage
        //private ImagemapMessage instance;

        public ImagemapMessageTests()
        {
            // TODO uncomment below to create an instance of ImagemapMessage
            //instance = new ImagemapMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImagemapMessage
        /// </summary>
        [Fact]
        public void ImagemapMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" ImagemapMessage
            //Assert.IsType<ImagemapMessage>(instance);
        }

        /// <summary>
        /// Test the property 'BaseUrl'
        /// </summary>
        [Fact]
        public void BaseUrlTest()
        {
            // TODO unit test for the property 'BaseUrl'
        }

        /// <summary>
        /// Test the property 'AltText'
        /// </summary>
        [Fact]
        public void AltTextTest()
        {
            // TODO unit test for the property 'AltText'
        }

        /// <summary>
        /// Test the property 'BaseSize'
        /// </summary>
        [Fact]
        public void BaseSizeTest()
        {
            // TODO unit test for the property 'BaseSize'
        }

        /// <summary>
        /// Test the property 'Actions'
        /// </summary>
        [Fact]
        public void ActionsTest()
        {
            // TODO unit test for the property 'Actions'
        }

        /// <summary>
        /// Test the property 'Video'
        /// </summary>
        [Fact]
        public void VideoTest()
        {
            // TODO unit test for the property 'Video'
        }
    }
}
