/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing IssueLinkTokenResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IssueLinkTokenResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IssueLinkTokenResponse
        //private IssueLinkTokenResponse instance;

        public IssueLinkTokenResponseTests()
        {
            // TODO uncomment below to create an instance of IssueLinkTokenResponse
            //instance = new IssueLinkTokenResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IssueLinkTokenResponse
        /// </summary>
        [Fact]
        public void IssueLinkTokenResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" IssueLinkTokenResponse
            //Assert.IsType<IssueLinkTokenResponse>(instance);
        }

        /// <summary>
        /// Test the property 'LinkToken'
        /// </summary>
        [Fact]
        public void LinkTokenTest()
        {
            // TODO unit test for the property 'LinkToken'
        }
    }
}
