/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing MentionTarget
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MentionTargetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MentionTarget
        //private MentionTarget instance;

        public MentionTargetTests()
        {
            // TODO uncomment below to create an instance of MentionTarget
            //instance = new MentionTarget();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MentionTarget
        /// </summary>
        [Fact]
        public void MentionTargetInstanceTest()
        {
            // TODO uncomment below to test "IsType" MentionTarget
            //Assert.IsType<MentionTarget>(instance);
        }

        /// <summary>
        /// Test deserialize a AllMentionTarget from type MentionTarget
        /// </summary>
        [Fact]
        public void AllMentionTargetDeserializeFromMentionTargetTest()
        {
            // TODO uncomment below to test deserialize a AllMentionTarget from type MentionTarget
            //Assert.IsType<MentionTarget>(JsonConvert.DeserializeObject<MentionTarget>(new AllMentionTarget().ToJson()));
        }

        /// <summary>
        /// Test deserialize a UserMentionTarget from type MentionTarget
        /// </summary>
        [Fact]
        public void UserMentionTargetDeserializeFromMentionTargetTest()
        {
            // TODO uncomment below to test deserialize a UserMentionTarget from type MentionTarget
            //Assert.IsType<MentionTarget>(JsonConvert.DeserializeObject<MentionTarget>(new UserMentionTarget().ToJson()));
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
