/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing OperatorDemographicFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OperatorDemographicFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OperatorDemographicFilter
        //private OperatorDemographicFilter instance;

        public OperatorDemographicFilterTests()
        {
            // TODO uncomment below to create an instance of OperatorDemographicFilter
            //instance = new OperatorDemographicFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OperatorDemographicFilter
        /// </summary>
        [Fact]
        public void OperatorDemographicFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" OperatorDemographicFilter
            //Assert.IsType<OperatorDemographicFilter>(instance);
        }

        /// <summary>
        /// Test the property 'And'
        /// </summary>
        [Fact]
        public void AndTest()
        {
            // TODO unit test for the property 'And'
        }

        /// <summary>
        /// Test the property 'Or'
        /// </summary>
        [Fact]
        public void OrTest()
        {
            // TODO unit test for the property 'Or'
        }

        /// <summary>
        /// Test the property 'Not'
        /// </summary>
        [Fact]
        public void NotTest()
        {
            // TODO unit test for the property 'Not'
        }
    }
}
