/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing QuotaConsumptionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QuotaConsumptionResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QuotaConsumptionResponse
        //private QuotaConsumptionResponse instance;

        public QuotaConsumptionResponseTests()
        {
            // TODO uncomment below to create an instance of QuotaConsumptionResponse
            //instance = new QuotaConsumptionResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QuotaConsumptionResponse
        /// </summary>
        [Fact]
        public void QuotaConsumptionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" QuotaConsumptionResponse
            //Assert.IsType<QuotaConsumptionResponse>(instance);
        }

        /// <summary>
        /// Test the property 'TotalUsage'
        /// </summary>
        [Fact]
        public void TotalUsageTest()
        {
            // TODO unit test for the property 'TotalUsage'
        }
    }
}
