/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing ReplyMessageRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReplyMessageRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReplyMessageRequest
        //private ReplyMessageRequest instance;

        public ReplyMessageRequestTests()
        {
            // TODO uncomment below to create an instance of ReplyMessageRequest
            //instance = new ReplyMessageRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReplyMessageRequest
        /// </summary>
        [Fact]
        public void ReplyMessageRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReplyMessageRequest
            //Assert.IsType<ReplyMessageRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ReplyToken'
        /// </summary>
        [Fact]
        public void ReplyTokenTest()
        {
            // TODO unit test for the property 'ReplyToken'
        }

        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Fact]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }

        /// <summary>
        /// Test the property 'NotificationDisabled'
        /// </summary>
        [Fact]
        public void NotificationDisabledTest()
        {
            // TODO unit test for the property 'NotificationDisabled'
        }
    }
}
