/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing RichMenuBatchUnlinkOperation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RichMenuBatchUnlinkOperationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RichMenuBatchUnlinkOperation
        //private RichMenuBatchUnlinkOperation instance;

        public RichMenuBatchUnlinkOperationTests()
        {
            // TODO uncomment below to create an instance of RichMenuBatchUnlinkOperation
            //instance = new RichMenuBatchUnlinkOperation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RichMenuBatchUnlinkOperation
        /// </summary>
        [Fact]
        public void RichMenuBatchUnlinkOperationInstanceTest()
        {
            // TODO uncomment below to test "IsType" RichMenuBatchUnlinkOperation
            //Assert.IsType<RichMenuBatchUnlinkOperation>(instance);
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
    }
}
