/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing RichMenuBatchRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RichMenuBatchRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RichMenuBatchRequest
        //private RichMenuBatchRequest instance;

        public RichMenuBatchRequestTests()
        {
            // TODO uncomment below to create an instance of RichMenuBatchRequest
            //instance = new RichMenuBatchRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RichMenuBatchRequest
        /// </summary>
        [Fact]
        public void RichMenuBatchRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RichMenuBatchRequest
            //Assert.IsType<RichMenuBatchRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Operations'
        /// </summary>
        [Fact]
        public void OperationsTest()
        {
            // TODO unit test for the property 'Operations'
        }

        /// <summary>
        /// Test the property 'ResumeRequestKey'
        /// </summary>
        [Fact]
        public void ResumeRequestKeyTest()
        {
            // TODO unit test for the property 'ResumeRequestKey'
        }
    }
}
