/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing RichMenuRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RichMenuRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RichMenuRequest
        //private RichMenuRequest instance;

        public RichMenuRequestTests()
        {
            // TODO uncomment below to create an instance of RichMenuRequest
            //instance = new RichMenuRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RichMenuRequest
        /// </summary>
        [Fact]
        public void RichMenuRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RichMenuRequest
            //Assert.IsType<RichMenuRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

        /// <summary>
        /// Test the property 'Selected'
        /// </summary>
        [Fact]
        public void SelectedTest()
        {
            // TODO unit test for the property 'Selected'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'ChatBarText'
        /// </summary>
        [Fact]
        public void ChatBarTextTest()
        {
            // TODO unit test for the property 'ChatBarText'
        }

        /// <summary>
        /// Test the property 'Areas'
        /// </summary>
        [Fact]
        public void AreasTest()
        {
            // TODO unit test for the property 'Areas'
        }
    }
}
