/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing StickerMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StickerMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StickerMessage
        //private StickerMessage instance;

        public StickerMessageTests()
        {
            // TODO uncomment below to create an instance of StickerMessage
            //instance = new StickerMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StickerMessage
        /// </summary>
        [Fact]
        public void StickerMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" StickerMessage
            //Assert.IsType<StickerMessage>(instance);
        }

        /// <summary>
        /// Test the property 'PackageId'
        /// </summary>
        [Fact]
        public void PackageIdTest()
        {
            // TODO unit test for the property 'PackageId'
        }

        /// <summary>
        /// Test the property 'StickerId'
        /// </summary>
        [Fact]
        public void StickerIdTest()
        {
            // TODO unit test for the property 'StickerId'
        }

        /// <summary>
        /// Test the property 'QuoteToken'
        /// </summary>
        [Fact]
        public void QuoteTokenTest()
        {
            // TODO unit test for the property 'QuoteToken'
        }
    }
}
