/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing TemplateMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplateMessage
        //private TemplateMessage instance;

        public TemplateMessageTests()
        {
            // TODO uncomment below to create an instance of TemplateMessage
            //instance = new TemplateMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplateMessage
        /// </summary>
        [Fact]
        public void TemplateMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemplateMessage
            //Assert.IsType<TemplateMessage>(instance);
        }

        /// <summary>
        /// Test the property 'AltText'
        /// </summary>
        [Fact]
        public void AltTextTest()
        {
            // TODO unit test for the property 'AltText'
        }

        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Fact]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }
    }
}
