/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing UserMentionTarget
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserMentionTargetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserMentionTarget
        //private UserMentionTarget instance;

        public UserMentionTargetTests()
        {
            // TODO uncomment below to create an instance of UserMentionTarget
            //instance = new UserMentionTarget();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserMentionTarget
        /// </summary>
        [Fact]
        public void UserMentionTargetInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserMentionTarget
            //Assert.IsType<UserMentionTarget>(instance);
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
    }
}
