/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.MessagingApi.Model;
using LineOpenApi.MessagingApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.MessagingApi.Test.Model
{
    /// <summary>
    ///  Class for testing UserProfileResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserProfileResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserProfileResponse
        //private UserProfileResponse instance;

        public UserProfileResponseTests()
        {
            // TODO uncomment below to create an instance of UserProfileResponse
            //instance = new UserProfileResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserProfileResponse
        /// </summary>
        [Fact]
        public void UserProfileResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserProfileResponse
            //Assert.IsType<UserProfileResponse>(instance);
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'PictureUrl'
        /// </summary>
        [Fact]
        public void PictureUrlTest()
        {
            // TODO unit test for the property 'PictureUrl'
        }

        /// <summary>
        /// Test the property 'StatusMessage'
        /// </summary>
        [Fact]
        public void StatusMessageTest()
        {
            // TODO unit test for the property 'StatusMessage'
        }

        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
    }
}
