/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.Webhook.Model;
using LineOpenApi.Webhook.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.Webhook.Test.Model
{
    /// <summary>
    ///  Class for testing ActionResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ActionResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ActionResult
        //private ActionResult instance;

        public ActionResultTests()
        {
            // TODO uncomment below to create an instance of ActionResult
            //instance = new ActionResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ActionResult
        /// </summary>
        [Fact]
        public void ActionResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" ActionResult
            //Assert.IsType<ActionResult>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
