/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.Webhook.Model;
using LineOpenApi.Webhook.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.Webhook.Test.Model
{
    /// <summary>
    ///  Class for testing BeaconContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BeaconContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BeaconContent
        //private BeaconContent instance;

        public BeaconContentTests()
        {
            // TODO uncomment below to create an instance of BeaconContent
            //instance = new BeaconContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BeaconContent
        /// </summary>
        [Fact]
        public void BeaconContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" BeaconContent
            //Assert.IsType<BeaconContent>(instance);
        }

        /// <summary>
        /// Test the property 'Hwid'
        /// </summary>
        [Fact]
        public void HwidTest()
        {
            // TODO unit test for the property 'Hwid'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Dm'
        /// </summary>
        [Fact]
        public void DmTest()
        {
            // TODO unit test for the property 'Dm'
        }
    }
}
