/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.Webhook.Model;
using LineOpenApi.Webhook.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.Webhook.Test.Model
{
    /// <summary>
    ///  Class for testing ChatControl
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChatControlTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChatControl
        //private ChatControl instance;

        public ChatControlTests()
        {
            // TODO uncomment below to create an instance of ChatControl
            //instance = new ChatControl();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChatControl
        /// </summary>
        [Fact]
        public void ChatControlInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChatControl
            //Assert.IsType<ChatControl>(instance);
        }

        /// <summary>
        /// Test the property 'ExpireAt'
        /// </summary>
        [Fact]
        public void ExpireAtTest()
        {
            // TODO unit test for the property 'ExpireAt'
        }
    }
}
