/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.Webhook.Model;
using LineOpenApi.Webhook.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.Webhook.Test.Model
{
    /// <summary>
    ///  Class for testing DeliveryContext
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeliveryContextTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeliveryContext
        //private DeliveryContext instance;

        public DeliveryContextTests()
        {
            // TODO uncomment below to create an instance of DeliveryContext
            //instance = new DeliveryContext();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeliveryContext
        /// </summary>
        [Fact]
        public void DeliveryContextInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeliveryContext
            //Assert.IsType<DeliveryContext>(instance);
        }

        /// <summary>
        /// Test the property 'IsRedelivery'
        /// </summary>
        [Fact]
        public void IsRedeliveryTest()
        {
            // TODO unit test for the property 'IsRedelivery'
        }
    }
}
