/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.Webhook.Model;
using LineOpenApi.Webhook.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.Webhook.Test.Model
{
    /// <summary>
    ///  Class for testing JoinedMembers
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JoinedMembersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JoinedMembers
        //private JoinedMembers instance;

        public JoinedMembersTests()
        {
            // TODO uncomment below to create an instance of JoinedMembers
            //instance = new JoinedMembers();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JoinedMembers
        /// </summary>
        [Fact]
        public void JoinedMembersInstanceTest()
        {
            // TODO uncomment below to test "IsType" JoinedMembers
            //Assert.IsType<JoinedMembers>(instance);
        }

        /// <summary>
        /// Test the property 'Members'
        /// </summary>
        [Fact]
        public void MembersTest()
        {
            // TODO unit test for the property 'Members'
        }
    }
}
