/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.Webhook.Model;
using LineOpenApi.Webhook.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.Webhook.Test.Model
{
    /// <summary>
    ///  Class for testing LinkThingsContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LinkThingsContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LinkThingsContent
        //private LinkThingsContent instance;

        public LinkThingsContentTests()
        {
            // TODO uncomment below to create an instance of LinkThingsContent
            //instance = new LinkThingsContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LinkThingsContent
        /// </summary>
        [Fact]
        public void LinkThingsContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" LinkThingsContent
            //Assert.IsType<LinkThingsContent>(instance);
        }

        /// <summary>
        /// Test the property 'DeviceId'
        /// </summary>
        [Fact]
        public void DeviceIdTest()
        {
            // TODO unit test for the property 'DeviceId'
        }
    }
}
