/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.Webhook.Model;
using LineOpenApi.Webhook.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.Webhook.Test.Model
{
    /// <summary>
    ///  Class for testing ModuleEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModuleEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModuleEvent
        //private ModuleEvent instance;

        public ModuleEventTests()
        {
            // TODO uncomment below to create an instance of ModuleEvent
            //instance = new ModuleEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModuleEvent
        /// </summary>
        [Fact]
        public void ModuleEventInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModuleEvent
            //Assert.IsType<ModuleEvent>(instance);
        }

        /// <summary>
        /// Test the property 'Module'
        /// </summary>
        [Fact]
        public void ModuleTest()
        {
            // TODO unit test for the property 'Module'
        }
    }
}
