/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.Webhook.Model;
using LineOpenApi.Webhook.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.Webhook.Test.Model
{
    /// <summary>
    ///  Class for testing RenewedMembershipContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RenewedMembershipContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RenewedMembershipContent
        //private RenewedMembershipContent instance;

        public RenewedMembershipContentTests()
        {
            // TODO uncomment below to create an instance of RenewedMembershipContent
            //instance = new RenewedMembershipContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RenewedMembershipContent
        /// </summary>
        [Fact]
        public void RenewedMembershipContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" RenewedMembershipContent
            //Assert.IsType<RenewedMembershipContent>(instance);
        }

        /// <summary>
        /// Test the property 'MembershipId'
        /// </summary>
        [Fact]
        public void MembershipIdTest()
        {
            // TODO unit test for the property 'MembershipId'
        }
    }
}
