/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.Webhook.Model;
using LineOpenApi.Webhook.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.Webhook.Test.Model
{
    /// <summary>
    ///  Class for testing ScenarioResultThingsContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScenarioResultThingsContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScenarioResultThingsContent
        //private ScenarioResultThingsContent instance;

        public ScenarioResultThingsContentTests()
        {
            // TODO uncomment below to create an instance of ScenarioResultThingsContent
            //instance = new ScenarioResultThingsContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScenarioResultThingsContent
        /// </summary>
        [Fact]
        public void ScenarioResultThingsContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" ScenarioResultThingsContent
            //Assert.IsType<ScenarioResultThingsContent>(instance);
        }

        /// <summary>
        /// Test the property 'DeviceId'
        /// </summary>
        [Fact]
        public void DeviceIdTest()
        {
            // TODO unit test for the property 'DeviceId'
        }

        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
    }
}
