/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.Webhook.Model;
using LineOpenApi.Webhook.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.Webhook.Test.Model
{
    /// <summary>
    ///  Class for testing Source
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SourceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Source
        //private Source instance;

        public SourceTests()
        {
            // TODO uncomment below to create an instance of Source
            //instance = new Source();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Source
        /// </summary>
        [Fact]
        public void SourceInstanceTest()
        {
            // TODO uncomment below to test "IsType" Source
            //Assert.IsType<Source>(instance);
        }

        /// <summary>
        /// Test deserialize a GroupSource from type Source
        /// </summary>
        [Fact]
        public void GroupSourceDeserializeFromSourceTest()
        {
            // TODO uncomment below to test deserialize a GroupSource from type Source
            //Assert.IsType<Source>(JsonConvert.DeserializeObject<Source>(new GroupSource().ToJson()));
        }

        /// <summary>
        /// Test deserialize a RoomSource from type Source
        /// </summary>
        [Fact]
        public void RoomSourceDeserializeFromSourceTest()
        {
            // TODO uncomment below to test deserialize a RoomSource from type Source
            //Assert.IsType<Source>(JsonConvert.DeserializeObject<Source>(new RoomSource().ToJson()));
        }

        /// <summary>
        /// Test deserialize a UserSource from type Source
        /// </summary>
        [Fact]
        public void UserSourceDeserializeFromSourceTest()
        {
            // TODO uncomment below to test deserialize a UserSource from type Source
            //Assert.IsType<Source>(JsonConvert.DeserializeObject<Source>(new UserSource().ToJson()));
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
