/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.Webhook.Model;
using LineOpenApi.Webhook.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.Webhook.Test.Model
{
    /// <summary>
    ///  Class for testing ThingsEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ThingsEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ThingsEvent
        //private ThingsEvent instance;

        public ThingsEventTests()
        {
            // TODO uncomment below to create an instance of ThingsEvent
            //instance = new ThingsEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ThingsEvent
        /// </summary>
        [Fact]
        public void ThingsEventInstanceTest()
        {
            // TODO uncomment below to test "IsType" ThingsEvent
            //Assert.IsType<ThingsEvent>(instance);
        }

        /// <summary>
        /// Test the property 'ReplyToken'
        /// </summary>
        [Fact]
        public void ReplyTokenTest()
        {
            // TODO unit test for the property 'ReplyToken'
        }

        /// <summary>
        /// Test the property 'Things'
        /// </summary>
        [Fact]
        public void ThingsTest()
        {
            // TODO unit test for the property 'Things'
        }
    }
}
