/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LineOpenApi.Webhook.Model;
using LineOpenApi.Webhook.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LineOpenApi.Webhook.Test.Model
{
    /// <summary>
    ///  Class for testing VideoPlayComplete
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VideoPlayCompleteTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VideoPlayComplete
        //private VideoPlayComplete instance;

        public VideoPlayCompleteTests()
        {
            // TODO uncomment below to create an instance of VideoPlayComplete
            //instance = new VideoPlayComplete();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VideoPlayComplete
        /// </summary>
        [Fact]
        public void VideoPlayCompleteInstanceTest()
        {
            // TODO uncomment below to test "IsType" VideoPlayComplete
            //Assert.IsType<VideoPlayComplete>(instance);
        }

        /// <summary>
        /// Test the property 'TrackingId'
        /// </summary>
        [Fact]
        public void TrackingIdTest()
        {
            // TODO unit test for the property 'TrackingId'
        }
    }
}
